export const services = [
  { id: "s1", name: "Signature Deep Tissue Massage", category: "spa", rating: 4.9, reviews: 128, price: 145, duration: "60 min", description: "A full-body deep tissue experience targeting chronic tension and muscle knots with premium aromatherapy oils.", location: "Downtown Wellness Center", specialist: "Elena Rossi", amenities: ["Steam Room", "Shower Suite", "Herbal Tea", "Robe & Slippers"], image: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?q=80&w=1000&auto=format&fit=crop" },
  { id: "s2", name: "HydraFacial Glow Treatment", category: "spa", rating: 4.8, reviews: 96, price: 160, duration: "45 min", description: "Multi-step facial combining cleansing, exfoliation, extraction, hydration and antioxidant protection.", location: "Raffine Flagship Spa", specialist: "Sofia Laurent", amenities: ["Private Suite", "LED Therapy", "Complimentary Serum"], image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=1000&auto=format&fit=crop" },
  { id: "s3", name: "Hot Stone Therapy", category: "spa", rating: 5.0, reviews: 74, price: 180, duration: "75 min", description: "Heated basalt stones combined with Swedish massage techniques for deep relaxation.", location: "Serenity Spa Lounge", specialist: "Maya Chen", amenities: ["Jacuzzi Access", "Aromatherapy", "Meditation Room"], image: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?q=80&w=1000&auto=format&fit=crop" },
  { id: "s4", name: "Precision Haircut & Styling", category: "hair", rating: 4.9, reviews: 210, price: 95, duration: "45 min", description: "Consultation-led precision cut with blow-dry styling by senior stylists.", location: "Raffine Hair Studio", specialist: "David Kim", amenities: ["Scalp Massage", "Premium Products", "Espresso Bar"], image: "https://images.unsplash.com/photo-1562322140-8baeececf3df?q=80&w=1000&auto=format&fit=crop" },
  { id: "s5", name: "Balayage Color Treatment", category: "hair", rating: 4.7, reviews: 87, price: 250, duration: "120 min", description: "Hand-painted highlights creating a natural, sun-kissed gradient using ammonia-free color.", location: "Studio Lumière", specialist: "Isabelle Moreau", amenities: ["Color Consultation", "Gloss Treatment", "Aftercare Kit"], image: "https://images.unsplash.com/photo-1560869713-7d0a29430803?q=80&w=1000&auto=format&fit=crop" },
  { id: "s6", name: "Keratin Smoothing Treatment", category: "hair", rating: 4.8, reviews: 63, price: 200, duration: "90 min", description: "Professional keratin treatment for frizz-free, silky smooth hair lasting up to 12 weeks.", location: "Raffine Hair Studio", specialist: "Nina Park", amenities: ["Heat Protectant", "Take-Home Shampoo", "Follow-up Consult"], image: "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?q=80&w=1000&auto=format&fit=crop" },
  { id: "s7", name: "Personal Training Session", category: "fitness", rating: 4.9, reviews: 156, price: 120, duration: "60 min", description: "One-on-one session with a certified trainer tailored to your fitness goals.", location: "Raffine Fitness Lab", specialist: "Marcus Reid", amenities: ["Body Composition Scan", "Protein Shake", "Towel Service"], image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1000&auto=format&fit=crop" },
  { id: "s8", name: "Group HIIT Class", category: "fitness", rating: 4.6, reviews: 230, price: 35, duration: "45 min", description: "High-intensity interval training in a motivating group setting with heart-rate tracking.", location: "Raffine Fitness Lab", specialist: "Jade Torres", amenities: ["Heart Rate Monitor", "Post-Class Smoothie", "Locker Room"], image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop" },
  { id: "s9", name: "Reformer Pilates", category: "fitness", rating: 4.8, reviews: 102, price: 65, duration: "50 min", description: "Machine-based pilates focusing on core strength, flexibility and posture alignment.", location: "Core Studio", specialist: "Lena Voss", amenities: ["Grip Socks", "Mat Rental", "Recovery Lounge"], image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000&auto=format&fit=crop" },
  { id: "s10", name: "Guided Meditation Session", category: "wellness", rating: 5.0, reviews: 89, price: 55, duration: "40 min", description: "Mindfulness meditation led by a certified practitioner in a sound-dampened studio.", location: "Mindful Space", specialist: "Aisha Patel", amenities: ["Sound Bath", "Herbal Tea", "Journal"], image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=1000&auto=format&fit=crop" },
  { id: "s11", name: "Ayurvedic Consultation", category: "wellness", rating: 4.9, reviews: 47, price: 130, duration: "60 min", description: "Holistic health assessment with personalized dosha analysis and lifestyle recommendations.", location: "Vedic Wellness Center", specialist: "Dr. Raj Sharma", amenities: ["Herbal Prescription", "Diet Plan", "Follow-up Call"], image: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?q=80&w=1000&auto=format&fit=crop" },
  { id: "s12", name: "Infrared Sauna Therapy", category: "wellness", rating: 4.7, reviews: 134, price: 45, duration: "30 min", description: "Full-spectrum infrared sauna session for detoxification, pain relief and relaxation.", location: "Serenity Spa Lounge", specialist: "Self-Service", amenities: ["Private Pod", "Cold Plunge", "Eucalyptus Towel"], image: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?q=80&w=1000&auto=format&fit=crop" },
];

export const products = [
  { id: "p1", name: "Midnight Radiance Oil", price: 85, description: "A luxurious blend of rosehip, jojoba, and vitamin E oils that deeply nourish while you sleep. Wake up to a luminous, dewy complexion.", rating: 4.9, reviews: 214, shades: ["Original", "Rose Gold", "Amber"], details: [{ label: "Ingredients", content: "Rosehip seed oil, jojoba oil, vitamin E, squalane, lavender essential oil." }, { label: "How to Use", content: "Apply 3-4 drops to clean skin before bed. Gently massage in upward motions." }, { label: "Shipping", content: "Free shipping on orders over ₹50. Arrives in 3-5 business days." }], image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?q=80&w=1000&auto=format&fit=crop" },
  { id: "p2", name: "Velvet Moisture Cloud", price: 42, description: "Weightless hydrating cream that melts into skin providing 72-hour moisture with hyaluronic acid and ceramides.", rating: 4.8, reviews: 178, details: [{ label: "Ingredients", content: "Hyaluronic acid, ceramides, niacinamide, shea butter, aloe vera." }, { label: "How to Use", content: "Apply generously to face and neck morning and evening after serum." }, { label: "Shipping", content: "Free shipping on orders over ₹50. Arrives in 3-5 business days." }], image: "https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?q=80&w=1000&auto=format&fit=crop" },
  { id: "p3", name: "Sculpting Stone Roller", price: 34, description: "Premium jade facial roller designed to reduce puffiness, improve circulation, and enhance product absorption.", rating: 4.7, reviews: 96, details: [{ label: "Materials", content: "Grade-A Xiuyan jade, stainless steel frame, silicone grip." }, { label: "How to Use", content: "Roll outward from center of face. Store in refrigerator for extra de-puffing." }, { label: "Shipping", content: "Free shipping on orders over ₹50. Arrives in 3-5 business days." }], image: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?q=80&w=1000&auto=format&fit=crop" },
  { id: "p4", name: "Purifying Essence Toner", price: 48, description: "A pH-balancing toner infused with witch hazel and green tea to refine pores and prep skin for hydration.", rating: 4.6, reviews: 152, details: [{ label: "Ingredients", content: "Witch hazel, green tea extract, centella asiatica, glycerin." }, { label: "How to Use", content: "Saturate a cotton pad and sweep across face after cleansing." }, { label: "Shipping", content: "Free shipping on orders over ₹50. Arrives in 3-5 business days." }], image: "https://images.unsplash.com/photo-1596462502278-27bfdc4033c8?q=80&w=1000&auto=format&fit=crop" },
];
